project_name: ssdutil

release:
  # Don't mark release as production ready if it contains a non-standard tag
  prerelease: auto

  # Don't auto publish the project in case something goes wrong
  draft: true

  # Override the name template to include the project name in a specific format
  name_template: "SSDUtil {{.Version}}"

before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...

builds:
  - <<: &build_defaults
    main: ./cmd/ssdutil/main.go
    binary: ssdutil
    ldflags:
      - -s -w -X github.com/Ruffel/ssdutil/internal/build.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin


builds:
  - <<: &build_defaults
      binary: ssdutil
      main: ./cmd/ssdutil/main.go
      ldflags:
        - -s -w -X github.com/Ruffel/ssdutil/internal/build.Version={{.Version}}
    id: linux
    goos: [linux]
    goarch: [386, amd64]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    replacements:
      darwin: macOS
    format: tar.gz

  - id: windows
    builds: [windows]
    format: zip
