project_name: ssdutil

release:
  # Don't mark release as production ready if it contains a non-standard tag
  prerelease: auto

  # Don't auto publish the project in case something goes wrong
  draft: true

  # Override the name template to include the project name in a specific format
  name_template: "SSDUtil {{.Version}}"

before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/ssdutil/main.go
    id: "cli"
    binary: ssdutil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: nix
    builds: [macos, linux]
    replacements:
      darwin: macOS
    format: tar.gz

  - id: windows
    builds: [windows]
    format: zip
