before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - main: ./cmd/ssdutil/main.go
    id: "cli"
    binary: ssdutil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

release:
  draft: true
  prerelease: auto
