on: [push, pull_request]

name: ssdutil
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: "run --timeout=30m"

  build:
    name: Build (${{ matrix.os }})
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [windows-2019, ubuntu-20.04, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code repository
        uses: actions/checkout@v2

      - name: Configure Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: Build the application
        run: go build ./cmd/ssdutil
