on: [push, pull_request]

name: Build and Test
jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x]
        os: [windows-2019, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: Check out code repository
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race ./...

      - name: Build the application
        run: go build -v ./cmd/ssdutil
